### ISSUE TITLE
Create an FAQ article about: "Create an event"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#1]
Create an FAQ article about: "Create an event"

**Comment by Elgayar** [comment]
@mariobehling Is there a specific format or template, or I shall create from Scratch?

**Comment by mariobehling** [comment]
There is no format yet. Just add a simple md file. Thank you.

**Comment by Elgayar** [comment]
I will, and if you wish, I can work on a template.

**Comment by mariobehling** [comment]
Please follow existing services first and iterate from there. See an example here http://help.eventnook.com/site/article/162310051/Create-an-event

**Comment by Elgayar** [comment]
I know the article format, I mean a template, like a better design instead of the Jekyll theme.

**Comment by mariobehling** [comment]
Sure, step by step: Right now the focus is really to get content. Theme is another area. We really need content and guides how to use eventyay. So, right now: Documentation in md files is the goal.

**Comment by Elgayar** [comment]
Will start working on it right away! ;D
