### ISSUE TITLE
Follow common text style and make article "How to add more sponsors into an event?" more formal

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#100]
The page is live here http://support.eventyay.com/event-setup/How-to-add-a-sponsors-listing-to-my-event.html

Please use a more neutral conversation style for the text, e.g. avoid "when you are happy", which sounds informal for example.

Also only make heading for content that really is a heading, e.g. "There are some simple steps in order to add extra sponsors" should not be a heading. 

Please go through the entire page and follow the same structure and style across the entire page and on all pages thereafter.

**Comment by bellaphan** [comment]
Fixed  #100
