### ISSUE TITLE
Fix numbering on "How to create an event"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#101]
There is a numbering with three times "1".
http://support.eventyay.com/event-setup/How-can-I-create-an-event.html

![Screenshot from 2020-08-30 14-31-28](https://user-images.githubusercontent.com/1583873/91659071-99ef1800-eacd-11ea-8f9b-541eef51f7d7.png)

**Comment by bellaphan** [comment]
Dear sir, I have check a few times, there might be something wrong with the web generator: 

This is what written in the code: 

<img width="1420" alt="Screen Shot 2020-08-31 at 9 41 00 pm" src="https://user-images.githubusercontent.com/50802607/91732799-eec88680-ebd2-11ea-8466-a592d51a3e99.png">

This is what appear on the web generator: 
<img width="1420" alt="Screen Shot 2020-08-31 at 9 41 44 pm" src="https://user-images.githubusercontent.com/50802607/91733029-3f3fe400-ebd3-11ea-8f74-b15b62dba7bd.png">

**Comment by bellaphan** [comment]
I will work it out
