### ISSUE TITLE
Create an article about the event set and "Select payment and currency"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#2]
Create an article about the event set and "Select payment and currency"

**Comment by oanarosca** [comment]
I'd like to take this up please :) Is it okay to put it in a folder, e.g `event-setup` to keep an organized structure?

**Comment by mariobehling** [comment]
Sure, thank you!

**Comment by oanarosca** [comment]
This issue can be closed as well.
