### ISSUE TITLE
How do I make my event private?

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/support.eventyay.com#21]
Hello I will be working on this : How to make my event private.

**Comment by NishithP2004** [comment]
https://docs.google.com/document/d/11is-zzz2x6pw7Y2LRkwiTbTjNxLHzSBMDzVgJq-ye0o

**Comment by NishithP2004** [comment]
https://docs.google.com/document/d/11is-zzz2x6pw7Y2LRkwiTbTjNxLHzSBMDzVgJq-ye0o

**Comment by Masquerade0097** [comment]
Resolved.
