### ISSUE TITLE
Responsiveness of the site

### ISSUE THREAD

**Issue by satcasm** [fossasia/support.eventyay.com#229]
In header the "m" of the h1 element gets inside of the "github" logo which doesn't looks good .

![image](https://user-images.githubusercontent.com/56315878/106378216-106bab00-63c9-11eb-8bf6-89dd56b61101.png)

**Comment by amanRT** [comment]
I started Working on this issue.

**Comment by rajnagdeo** [comment]
can u tell me how so you solve the issue I am new to this

> I started Working on this issue.

**Comment by Ajaygupta22** [comment]
@satcasm i would like to work on it but can u pls help me with the file name?

**Comment by iamdevvalecha** [comment]
@satcasm it's working fine please close this pr.
