### ISSUE TITLE
missing page "How much does it cost to use eventyay?"

### ISSUE THREAD

**Issue by dsugrobov** [fossasia/support.eventyay.com#52]
Seems one of the most important pages is missing and for now the pricing policy is not clear.

The link on the main page drives me to `404`: http://support.eventyay.com/How-much-does-it-cost-to-use-eventyay

**Comment by sunnystark** [comment]
I want to work on that issue

**Comment by mariobehling** [comment]
This is all work in progress. Info will be published on the main site in upcoming days.
