### ISSUE TITLE
Parent Issue: Marketing & Analytics

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#72]
- [x] How to include images in event details?
- [x] How to add a Twitter account feed to your event page?

**Comment by edenyay** [comment]
> * [x]  How to include images in event details? fixed by https://github.com/fossasia/support.eventyay.com/pull/94
> * [x]  How to add a Twitter account feed to your event page? fixed by https://github.com/fossasia/support.eventyay.com/pull/89
