### ISSUE TITLE
Create Article: How can I add a form to collect attendee information?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#80]
We need the article: "How can I add a form to collect attendee information?" with images and description.

Related to https://github.com/fossasia/support.eventyay.com/issues/62

**Comment by mariobehling** [comment]
Please also show how to access this feature
a) When an organizer creates an event.
b) How to access this feature from the event dashboard.

**Comment by bellaphan** [comment]
Fixed #120
