### ISSUE TITLE
Create Article: How to add additional information such as event type, links, refund policy, terms and conditions, and code of conduct?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#81]
We need an article about: "How to add additional information such as event type, links, refund policy, terms and conditions, and code of conduct?" 

Add information and screenshots.

Related to Parent Issue: https://github.com/fossasia/support.eventyay.com/issues/62

**Comment by mariobehling** [comment]
Reopening this issue. There is a broken image on this page. Please correct this as well: http://support.eventyay.com/event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.html

**Comment by bellaphan** [comment]
sure sir

**Comment by bellaphan** [comment]
Yes sir

**Comment by bellaphan** [comment]
https://github.com/bellaphan/support.eventyay.com-1/blob/master/event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md

Done!
