### ISSUE TITLE
Create an article about How do I sell tickets online with eventyay?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#9]
Create an article about How do I sell tickets online with eventyay?

**Comment by oanarosca** [comment]
Isn't this a duplicate of select payment and currency?

**Comment by mariobehling** [comment]
There is always an overlap, but these are the questions people are looking for. Feel free to take some inspiration here: http://help.eventnook.com/site/article/162910100/How-do-I-sell-tickets-online-with-EventNook

**Comment by zohaayasser** [comment]
Pls find the below link of how to sell tickets online 
https://codein.withgoogle.com/serve/6599694386987008/
