### ISSUE TITLE
Fix how to add sponsors page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#96]
1. Correct heading use exact same question on overview site instead of "How to add more sponsors into an event?"
2. Take this out: There are some simple steps in order to add extra sponsors
3. Change heading 3 to heading 2 levels

**Comment by bellaphan** [comment]
I think this issue might have the same content as: https://github.com/bellaphan/support.eventyay.com-1/blob/master/event-setup/How-to-add-a-sponsors-listing-to-my-event.md

So, the issue #96 might have been done already
