### ISSUE TITLE
Update and Fix Title of page "How do I sell tickets online?"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#98]
In the tickets and payments list there is an article that does not show the same heading as on the start page "https://support.eventyay.com/tickets-payments/How-do-I-sell-tickets-online.html".

The images are outdated and the text is not currenct.

Delete the images and create new images.

Also include information on where the tickets who up and how people can order the tickets.

Related to https://github.com/fossasia/support.eventyay.com/issues/65

**Comment by bellaphan** [comment]
https://github.com/bellaphan/support.eventyay.com-1/blob/master/tickets-payments/How-do-I-sell-tickets-online.md

Dear sir, this is what I have done so far in this issue, it stills need to little more enhancement. I will create a PR tomorrow, and continue with other issues
