### ISSUE TITLE
Fix title and images of How to add a Twitter feed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/support.eventyay.com#99]
* The title is not exactly the same as on the overview page. Please make it exactly the same. Use "event page" instead of "event-page" and add a question mark.
* Images are broken. 
  * The image embed added is https://github.com/fossasia/support.eventyay.com/blob/master/images/How-to-add-a-Twitter-account-feed-to-your-event-page1.png 
  * Correct is /images/How-to-add-a-Twitter-account-feed-to-your-event-page1.png

**Comment by edenyay** [comment]
@mariobehling could you review the PR?
